Repository penpot/penpot, pull requests merged in 2025-08, with the labels that each got.

#7036 :bug: Fix text style change not being applied
  CHANGES.md
  frontend/playwright/data/text-editor/get-file-11552.json
  frontend/playwright/data/text-editor/update-file-11552.json
  frontend/playwright/ui/pages/WorkspacePage.js
  frontend/playwright/ui/specs/text-editor-v2.spec.js
  frontend/src/app/main/ui/workspace/shapes/text/v2_editor.cljs
  frontend/text-editor/src/editor/content/dom/Inline.js
  frontend/text-editor/src/editor/content/dom/Paragraph.js
  frontend/text-editor/src/editor/controllers/SelectionController.js
Labels: new render

#7048 :sparkles: Include symbols support
  frontend/playwright/data/render-wasm/assets/notomusicsubset.ttf
  frontend/playwright/data/render-wasm/assets/notosanssymbols2subset.ttf
  frontend/playwright/data/render-wasm/assets/notosanssymbolssubset.ttf
  frontend/playwright/data/render-wasm/get-file-text-symbols.json
  frontend/playwright/ui/render-wasm-specs/texts.spec.js
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-texts-with-emoji-and-different-symbols-1.png
  frontend/src/app/render_wasm/api/fonts.cljs
  frontend/src/app/render_wasm/api/texts.cljs
Labels: new render

#7073 :sparkles: Treat empty names as a malformed formula
  common/src/app/common/logic/variant_properties.cljc
  frontend/src/app/main/data/workspace/variants.cljs
  frontend/src/app/main/ui/workspace/sidebar/layer_name.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
Labels: variants

#7065 :bug: Fix focus new added property
  common/src/app/common/files/variant.cljc
  common/src/app/common/logic/variant_properties.cljc
  frontend/src/app/main/ui/ds/product/input_with_meta.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets/common.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
Labels: variants

#7079 :bug: Fix selection lost when using keyboard
  frontend/src/app/main/data/workspace/transforms.cljs
Labels: new render

#7080 :bug: Add missing generator for token-set file change operation
  backend/src/app/rpc/commands/files_thumbnails.clj
  common/src/app/common/files/changes.cljc
  common/src/app/common/types/tokens_lib.cljc
Labels: hotfix

#7041 :sparkles: Add wasm boolean calculations
  common/src/app/common/types/fills/impl.cljc
  common/src/app/common/types/path.cljc
  common/src/app/common/types/path/impl.cljc
  frontend/src/app/main/data/workspace/path/shapes_to_path.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/bool.cljs
  frontend/src/app/plugins/register.cljs
  frontend/src/app/render_wasm.cljs
  frontend/src/app/render_wasm/api.cljs
  frontend/src/app/render_wasm/api/texts.cljs
  frontend/src/app/render_wasm/mem.cljs
  frontend/src/app/render_wasm/serializers.cljs
  render-wasm/Cargo.lock
  render-wasm/Cargo.toml
  render-wasm/src/main.rs
  render-wasm/src/math.rs
  render-wasm/src/math/bools.rs
  render-wasm/src/render.rs
  render-wasm/src/render/fonts.rs
  render-wasm/src/shapes.rs
  render-wasm/src/shapes/modifiers.rs
  render-wasm/src/shapes/paths.rs
  render-wasm/src/shapes/shape_to_path.rs
  render-wasm/src/shapes/text.rs
  render-wasm/src/shapes/text_paths.rs
  render-wasm/src/wasm/paths.rs
Labels: new render

#7092 :bug: Fix artifacts while panning in wasm render
  render-wasm/src/render.rs
  render-wasm/src/render/surfaces.rs
  render-wasm/src/state.rs
Labels: new render

#7116 :bug: Fix flick on design tab after variant switch
  frontend/src/app/main/data/workspace/libraries.cljs
  frontend/src/app/main/ui/ds/controls/select.cljs
Labels: variants

#7113 :wrench: Update multiple emoji test and increase resulting image
  frontend/playwright/data/render-wasm/get-file-text-emoji-board.json
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-multiple-emoji-1.png
Labels: new render

#7143 :sparkles: Adjust the appearance of the variant-related elements in the design tab
  frontend/src/app/main/ui/components/title_bar.cljs
  frontend/src/app/main/ui/inspect/annotation.cljs
  frontend/src/app/main/ui/inspect/attributes/layout_element.cljs
  frontend/src/app/main/ui/inspect/exports.cljs
  frontend/src/app/main/ui/workspace/libraries.cljs
  frontend/src/app/main/ui/workspace/plugins.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets/common.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets/file_library.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets/groups.cljs
  frontend/src/app/main/ui/workspace/sidebar/layers.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/blur.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/color_selection.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
  frontend/src/app/main/ui/workspace/sidebar/options/menus/constraints.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/exports.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/fill.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/frame_grid.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/grid_cell.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/interactions.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/layout_container.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/layout_item.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/shadow.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/stroke.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/svg_attrs.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/text.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/page.cljs
  frontend/src/app/main/ui/workspace/sidebar/sitemap.cljs
  frontend/src/app/main/ui/workspace/tokens/sidebar.cljs
Labels: variants

#7152 :tada: Update skia binares to 0.87.0
  render-wasm/Cargo.lock
  render-wasm/Cargo.toml
  render-wasm/build
  render-wasm/lint
  render-wasm/test
  render-wasm/watch
  render-wasm/watch_test
Labels: new render

#7154 :bug: Fix incorrect show request-access dialog on not-found on viewer
  frontend/src/app/main/ui/static.cljs
Labels: hotfix

#7170 :wrench: Update and fix text tests
  frontend/playwright/data/render-wasm/assets/notocoloremojisubset.ttf
  frontend/playwright/data/render-wasm/get-file-emoji-and-text-decoration.json
  frontend/playwright/data/render-wasm/get-file-text-decoration.json
  frontend/playwright/data/render-wasm/get-file-text-styles.json
  frontend/playwright/ui/render-wasm-specs/texts.spec.js
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-emoji-and-text-decoration-1.png
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-styled-texts-1.png
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-text-decoration-1.png
  frontend/playwright/ui/render-wasm-specs/texts.spec.js-snapshots/Renders-a-file-with-texts-with-images-1.png
  frontend/src/app/render_wasm/api/texts.cljs
  render-wasm/src/render.rs
  render-wasm/src/shapes.rs
  render-wasm/src/shapes/text.rs
Labels: new render

#7145 :sparkles: Update code to use design system icon
  frontend/playwright/ui/specs/variants.spec.js
  frontend/src/app/main/ui/components/shape_icon.cljs
  frontend/src/app/main/ui/ds/foundations/assets/icon.cljs
  frontend/src/app/main/ui/inspect/attributes/stroke.cljs
  frontend/src/app/main/ui/inspect/right_sidebar.cljs
  frontend/src/app/main/ui/inspect/right_sidebar.scss
  frontend/src/app/main/ui/workspace/context_menu.cljs
  frontend/src/app/main/ui/workspace/sidebar/layer_item.cljs
  frontend/src/app/main/ui/workspace/sidebar/layer_item.scss
  frontend/src/app/main/ui/workspace/sidebar/layers.cljs
  frontend/src/app/main/ui/workspace/sidebar/layers.scss
  frontend/src/app/util/shape_icon.cljs
Labels: tokens

#7173 :bug: Fix paragraph layout width on autowidth
  frontend/src/app/render_wasm/serializers.cljs
  render-wasm/src/render.rs
  render-wasm/src/render/text.rs
  render-wasm/src/shapes/modifiers.rs
  render-wasm/src/shapes/text.rs
  render-wasm/src/shapes/text_paths.rs
  render-wasm/src/wasm/text.rs
Labels: new render

#7174 :sparkles: Make some improvements to the swap panel
  frontend/src/app/main/ui/components/search_bar.cljs
  frontend/src/app/main/ui/components/search_bar.scss
  frontend/src/app/main/ui/workspace/libraries.cljs
  frontend/src/app/main/ui/workspace/plugins.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets.cljs
  frontend/src/app/main/ui/workspace/sidebar/assets/components.scss
  frontend/src/app/main/ui/workspace/sidebar/layers.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
  frontend/src/app/main/ui/workspace/sidebar/options/menus/typography.cljs
  frontend/src/app/main/ui/workspace/sidebar/shortcuts.cljs
Labels: variants

#7181 :sparkles: Add shortcuts for creating variants and properties
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
Labels: variants

#7166 :tada: Inspect tab layout switcher and computed feature
  common/src/app/common/flags.cljc
  frontend/src/app/main/ui/inspect/right_sidebar.cljs
  frontend/src/app/main/ui/inspect/right_sidebar.scss
  frontend/src/app/main/ui/inspect/styles.cljs
  frontend/src/app/main/ui/inspect/styles/style_box.cljs
  frontend/translations/en.po
  frontend/translations/es.po
Labels: tokens

#7204 :bug: Fix color of variant property names in the design tab
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
Labels: variants

#7200 :bug: Fix new inline text styles not being applied correctly
  frontend/src/app/main/data/workspace/texts.cljs
Labels: new render

#7195 :sparkles: Show create variant shortcut also for stand-alone components
  frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
Labels: variants

#7175 :bug: Fix clipping
  render-wasm/src/render.rs
Labels: new render

#7219 :bug: Fix token create not disabled when creating token without value
  frontend/playwright/ui/specs/tokens.spec.js
  frontend/src/app/main/ui/workspace/tokens/management/create/form.cljs
Labels: tokens

#7187 :tada: Inspect styles tab attributes container box
  frontend/src/app/main/ui/inspect/right_sidebar.scss
  frontend/src/app/main/ui/inspect/styles.cljs
  frontend/src/app/main/ui/inspect/styles/style_box.cljs
  frontend/src/app/main/ui/inspect/styles/style_box.scss
  frontend/translations/en.po
  frontend/translations/es.po
Labels: tokens
