Repository penpot/penpot, pull requests merged in 2025-02, with the labels that each got.

#5766 :sparkles: Several changes to tokens
  frontend/src/app/main/data/tokens.cljs
  frontend/src/app/main/data/workspace/tokens/common.cljs
  frontend/src/app/main/data/workspace/tokens/selected_set.cljs
  frontend/src/app/main/refs.cljs
  frontend/src/app/main/ui/workspace/sidebar.cljs
  frontend/src/app/main/ui/workspace/tokens/changes.cljs
  frontend/src/app/main/ui/workspace/tokens/context_menu.cljs
  frontend/src/app/main/ui/workspace/tokens/form.cljs
  frontend/src/app/main/ui/workspace/tokens/sidebar.cljs
  frontend/src/app/main/ui/workspace/tokens/style_dictionary.cljs
  frontend/src/app/main/ui/workspace/tokens/theme_select.cljs
  frontend/src/app/main/ui/workspace/tokens/token.cljs
  frontend/src/app/main/ui/workspace/tokens/token_pill.cljs
  frontend/src/app/main/ui/workspace/tokens/token_types.cljs
  frontend/src/app/util/array.cljs
Labels: ready to merge

#5858 :bug: Fix opacity in frame containers
  frontend/src/app/main/ui/shapes/frame.cljs
  frontend/src/app/main/ui/workspace/shapes/frame.cljs
Labels: bug

#5918 :sparkles: Improve readability of RGBA and HSLA values in inspect mode
  common/src/app/common/colors.cljc
  common/src/app/common/data.cljc
  common/test/common_tests/colors_test.cljc
  frontend/src/app/main/ui/inspect/attributes/common.cljs
  frontend/src/app/util/color.cljs
Labels: design, easy fix
